version: "3"

services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    env_file: .env
    volumes:
      - db-data:/var/lib/mysql

  drupal:
    image: drupal:9.2.10
    container_name: drupal
    depends_on:
      - mysql
    restart: unless-stopped
    ports:
      - 8080:80
    volumes:
      - drupal-modules:/var/www/html/modules
      - drupal-profiles:/var/www/html/profiles
      - type: bind
        source: ./data/drupal/sites
        target: /var/www/html/sites
      - drupal-themes:/var/www/html/themes

volumes:
  drupal-modules:
  drupal-profiles:
  drupal-themes:
  db-data:
